---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      APP_ENV: prod
      APP_DEBUG: 0
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  # Next.js Frontend Production
  frontend:
    build:
      context: ./frontend
      target: runner
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://wtracker.bieda.it/api/v1
      - HOSTNAME=0.0.0.0
      - PORT=3000
