# Docker Compose override for development
# Use: docker compose -f compose.yaml -f compose.dev.yaml up

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps  # Use only deps stage for development
    command: npm run dev
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/next.config.js:/app/next.config.js:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.js:/app/postcss.config.js:ro
      # Exclude node_modules and .next from being mounted
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable polling for Docker

